/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas10_no2_asleb_muhamad.rafy.ramadhan;

import javax.swing.ImageIcon;

/**
 *
 * @author Rafy1
 */
public class Kalkulator_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulator_GUI.class.getName());
    
    String angka;
    String tampil1 = "", tampil2 = "";
    String simbol = "";
    double total, bil1 = 0, bil2 = 0;
    int pil;
    

    /**
     * Creates new form Kalkulator_GUI
     */
    public Kalkulator_GUI() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasil = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        modulus = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        angka7 = new javax.swing.JButton();
        angka4 = new javax.swing.JButton();
        angka1 = new javax.swing.JButton();
        angka0 = new javax.swing.JButton();
        angka8 = new javax.swing.JButton();
        angka5 = new javax.swing.JButton();
        angka2 = new javax.swing.JButton();
        angka3 = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        angka6 = new javax.swing.JButton();
        angka9 = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        eksponen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("logoCal.png")).getImage());
        setName("kalkulator"); // NOI18N
        setResizable(false);

        hasil.setEditable(false);
        hasil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(255, 204, 0));
        hapus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hapus.setText("C");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        modulus.setBackground(new java.awt.Color(255, 204, 0));
        modulus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        modulus.setText("%");
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });

        pembagian.setBackground(new java.awt.Color(255, 204, 0));
        pembagian.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pembagian.setText("/");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });

        angka7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka7.setText("7");
        angka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka7ActionPerformed(evt);
            }
        });

        angka4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka4.setText("4");
        angka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka4ActionPerformed(evt);
            }
        });

        angka1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka1.setText("1");
        angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ActionPerformed(evt);
            }
        });

        angka0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka0.setText("0");
        angka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka0ActionPerformed(evt);
            }
        });

        angka8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka8.setText("8");
        angka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka8ActionPerformed(evt);
            }
        });

        angka5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka5.setText("5");
        angka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka5ActionPerformed(evt);
            }
        });

        angka2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka2.setText("2");
        angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ActionPerformed(evt);
            }
        });

        angka3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka3.setText("3");
        angka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka3ActionPerformed(evt);
            }
        });

        koma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        koma.setText(",");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });

        angka6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka6.setText("6");
        angka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka6ActionPerformed(evt);
            }
        });

        angka9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka9.setText("9");
        angka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka9ActionPerformed(evt);
            }
        });

        samadengan.setBackground(new java.awt.Color(255, 204, 0));
        samadengan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });

        kurang.setBackground(new java.awt.Color(255, 204, 0));
        kurang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        tambah.setBackground(new java.awt.Color(255, 204, 0));
        tambah.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        kali.setBackground(new java.awt.Color(255, 204, 0));
        kali.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 204, 0));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas10_no2_asleb_muhamad/rafy/ramadhan/delete.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        eksponen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eksponen.setText("E");
        eksponen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksponenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasil)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modulus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(angka7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(angka4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eksponen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(angka8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(angka5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(angka2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(angka0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(angka6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(angka9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kali, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modulus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angka9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angka6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(koma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kali, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eksponen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void angka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            return;
        }
        
        angka += "0";       
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka0ActionPerformed

    private void angka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "3";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka3ActionPerformed

    private void angka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "6";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka6ActionPerformed

    private void angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "1";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka1ActionPerformed

    private void angka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "2";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka2ActionPerformed

    private void angka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "4";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka4ActionPerformed

    private void angka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "5";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka5ActionPerformed

    private void angka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "7";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka7ActionPerformed

    private void angka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "8";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka8ActionPerformed

    private void angka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ActionPerformed
        if(!(total == 0)){
            total = 0;
        }
        
        if(angka.equals("0")){
            angka = "";
        }
        
        angka += "9";
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_angka9ActionPerformed

    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed

        if(!(total == 0)){
            bil1 = total;
        } else {
            if(angka.length() == 0){
                return;
            }
            bil1 = Double.parseDouble(angka);
        }
        
        if(bil1 % 1 == 0){
            tampil1 = Integer.toString((int) bil1);
        } else {
            tampil1 = Double.toString(bil1);
        }
        
        simbol = " % ";
        hasil.setText(tampil1 + simbol);
        angka = "";
        pil = 5;
    }//GEN-LAST:event_modulusActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if(!(total == 0)){
            bil1 = total;
        } else {
            if(angka.length() == 0){
                return;
            }
            bil1 = Double.parseDouble(angka);
        }
        
        if(bil1 % 1 == 0){
            tampil1 = Integer.toString((int) bil1);
        } else {
            tampil1 = Double.toString(bil1);
        }
       
        
        simbol = "+";
        hasil.setText(tampil1 + simbol);
        angka = "";
        pil = 1;
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed

        if(!(total == 0)){
            bil1 = total;
        } else {
            if(angka.length() == 0){
                return;
            }
            bil1 = Double.parseDouble(angka);
        }
        
        if(bil1 % 1 == 0){
            tampil1 = Integer.toString((int) bil1);
        } else {
            tampil1 = Double.toString(bil1);
        }
        
        simbol = " - ";
        hasil.setText(tampil1 + simbol);
        System.out.println(tampil1 + simbol);
        angka = "";
        pil = 2;
    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed

        if(!(total == 0)){
            bil1 = total;
        } else {
            if(angka.length() == 0){
                return;
            }
            bil1 = Double.parseDouble(angka);
        }
        
        if(bil1 % 1 == 0){
            tampil1 = Integer.toString((int) bil1);
        } else {
            tampil1 = Double.toString(bil1);
        }
        
        simbol = " X ";
        hasil.setText(tampil1 + simbol);
        angka = "";
        pil = 3;
    }//GEN-LAST:event_kaliActionPerformed

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed

        if(!(total == 0)){
            bil1 = total;
        } else {
            if(angka.length() == 0){
                return;
            }
            bil1 = Double.parseDouble(angka);
        }
        
        if(bil1 % 1 == 0){
            tampil1 = Integer.toString((int) bil1);
        } else {
            tampil1 = Double.toString(bil1);
        }
        
        simbol = " / ";
        hasil.setText(tampil1 + simbol);
        angka = "";
        pil = 4;
    }//GEN-LAST:event_pembagianActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        if(angka.length() == 0){
            return;
        }
        
        angka += ".";
        
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_komaActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        bil1 = 0;
        bil2 = 0;
        total = 0;
        angka = "";
        tampil1 = "";
        tampil2 = "";
        simbol = "";
        hasil.setText(angka);
    }//GEN-LAST:event_hapusActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        switch(pil){
            case 1:
                if(angka.length() == 0){
                    break;
                }
                
                bil2 = Double.parseDouble(angka);
                total = bil1 + bil2; 
                
                if(total % 1 == 0){
                    hasil.setText(Integer.toString((int) total));
                } else {
                    hasil.setText(Double.toString(total));
                }
                
                
                angka = "";
                bil1 = 0;
                bil2 = 0;
                pil = 0;
                tampil1 = "";
                tampil2 = "";
                simbol = "";
                break;
            case 2:
                if(angka.length() == 0){
                    break;
                }
                
                bil2 = Double.parseDouble(angka);
                total = bil1 - bil2;
                
                if(total % 1 == 0){
                    hasil.setText(Integer.toString((int) total));
                } else {
                    hasil.setText(Double.toString(total));
                }
                
                angka = "";
                bil1 = 0;
                bil2 = 0;
                pil = 0;
                tampil1 = "";
                tampil2 = "";
                simbol = "";
                break;
            case 3:
                if(angka.length() == 0){
                    break;
                }
                
                bil2 = Double.parseDouble(angka);
                total = bil1 * bil2;
                
                if(total % 1 == 0){
                    hasil.setText(Integer.toString((int) total));
                } else {
                    hasil.setText(Double.toString(total));
                }
                
                angka = "";
                bil1 = 0;
                bil2 = 0;
                pil = 0;
                tampil1 = "";
                tampil2 = "";
                simbol = "";
                break;
            case 4:
                if(angka.length() == 0){
                    break;
                }
                
                bil2 = Double.parseDouble(angka);
                total = bil1 / bil2;
                
                if(total % 1 == 0){
                    hasil.setText(Integer.toString((int) total));
                } else {
                    hasil.setText(Double.toString(total));
                }
                
                angka = "";
                bil1 = 0;
                bil2 = 0;
                pil = 0;
                tampil1 = "";
                tampil2 = "";
                simbol = "";
                break;
            case 5:
                if(angka.length() == 0){
                    break;
                }
                
                bil2 = Double.parseDouble(angka);
                total = bil1 % bil2;
                
                if(total % 1 == 0){
                    hasil.setText(Integer.toString((int) total));
                } else {
                    hasil.setText(Double.toString(total));
                }
                
                angka = "";
                bil1 = 0;
                bil2 = 0;
                pil = 0;
                tampil1 = "";
                tampil2 = "";
                simbol = "";
                break;
            case 6:
                if(angka.length() == 0){
                    break;
                }
                
                bil2 = Double.parseDouble(angka);
                bil2 = Math.pow(10, bil2);
                total = bil1 * bil2;
                
                if(total % 1 == 0){
                    hasil.setText(Integer.toString((int) total));
                } else {
                    hasil.setText(Double.toString(total));
                }
                
                angka = "";
                bil1 = 0;
                bil2 = 0;
                pil = 0;
                tampil1 = "";
                tampil2 = "";
                simbol = "";
                break;
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(angka.length() == 1 || angka.length() == 0){
            angka = "";
            if(tampil1 == ""){
                hasil.setText(angka);
            } else {
                hasil.setText(tampil1 + simbol + angka);
            }
            return;
        } 
        
        angka = angka.substring(0, angka.length() - 1);
        if(tampil1 == ""){
            hasil.setText(angka);
        } else {
            hasil.setText(tampil1 + simbol + angka);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void eksponenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksponenActionPerformed
        if(!(total == 0)){
            bil1 = total;
        } else {
            bil1 = Double.parseDouble(angka);
        }
        
        if(bil1 % 1 == 0){
            tampil1 = Integer.toString((int) bil1);
        }
        
        simbol = " E";
        hasil.setText(tampil1 + simbol); 
        angka = "";
        pil = 6;
    }//GEN-LAST:event_eksponenActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angka0;
    private javax.swing.JButton angka1;
    private javax.swing.JButton angka2;
    private javax.swing.JButton angka3;
    private javax.swing.JButton angka4;
    private javax.swing.JButton angka5;
    private javax.swing.JButton angka6;
    private javax.swing.JButton angka7;
    private javax.swing.JButton angka8;
    private javax.swing.JButton angka9;
    private javax.swing.JButton delete;
    private javax.swing.JButton eksponen;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton modulus;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
